<?php echo $this->mainNavbar; ?>

<!-- Begin page content -->
<div class="container container-page">
    <div class="page-header">
        <h1><?php echo $this->translate('confirm_title'); ?></h1>
    </div>
    <p class="lead"><?php echo $this->translate('confirm_info_text'); ?></p>

    <form method="post" action="<?php echo $this->url('submit'); ?>">

        <?php if (!$this->candidates->count()) { ?>
        <p><?php echo $this->translate('no_candidates_selected'); ?></p>
        <?php } ?>
        <?php foreach ($this->candidates as $candidate) { ?>
        <div class="checkbox">
            <label><?php 
            printf("<strong><a href=\"mailto:%s\">%s %s</a></strong>", $candidate->getEmail(),$candidate->getFirstName(), $candidate->getLastName());
            ?></label> <input type="hidden" name="candidates[]" value="<?php echo $candidate->getId(); ?>">
        </div>
        <?php } ?>

        <br> 
        <input type="hidden" name="role" value="<?php echo $this->role; ?>"> 
        <input type="hidden" name="fuu" value="<?php echo $this->csrfToken; ?>">        
        
        <input type="submit" name="submit" value="<?php echo $this->translate('confirm_vote_submit'); ?>" class="btn btn-primary">
        <br>
        <a href="<?php echo $this->url('form'); ?>" class="btn">&laquo; <?php echo $this->translate('button_start_over'); ?></a>
    </form>

</div>