<?php echo $this->mainNavbar; ?>

<!-- Begin page content -->
<div class="container container-page">
    <div class="page-header">
        <h1><?php echo $this->translate($this->errorTitle); ?></h1>
    </div>
    <p class="lead"><?php echo $this->translate($this->errorMessage); ?></p>

    <a type="button" class="btn btn-danger" href="<?php echo $this->url('index'); ?>"><?php echo $this->translate('button_start_over'); ?></a>
</div>