<?php echo $this->mainNavbar; ?>

<!-- BEGIN page container -->
<div class="container container-page">
    <div class="page-header">
        <h1><?php echo $this->translate('form_title'); ?></h1>
    </div>
    <p class="lead"><?php echo $this->translate('form_info_text'); ?></p>
    
    <?php if ($this->countRestriction) { ?>
    <p><?php printf("%s: %d", $this->translate('form_vote_count_restriction'), $this->countRestriction); ?></p>
    <?php } ?>

    <form method="post" action="confirm">

        <?php foreach ($this->candidates as $candidate) { ?>
        <div class="checkbox">
            <label> <input type="checkbox" name="candidates[]" value="<?php echo $candidate->getId(); ?>"><?php
            printf("<strong>%s %s</strong>", $candidate->getFirstName(), $candidate->getLastName());
            printf(" (<a href=\"%s\" target=\"_blank\">%s</a>)", $candidate->getCandidateUrl(), $this->translate('candidate_url'));
            ?></label>
        </div>
        <?php } ?>

        <br> 
        <input type="hidden" name="role" value="<?php echo $this->role; ?>"> 
        <input type="hidden" name="fuu" value="<?php echo $this->csrfToken; ?>">
        <input type="submit" name="submit" value="<?php echo $this->translate('form_vote_submit'); ?>" class="btn btn-primary">
    </form>
</div>
<!-- END page container -->

