
<?php echo $this->mainNavbar; ?>


<!-- Begin page content -->
<div class="container container-page">
    <div class="page-header">
        <h1><?php echo $this->heading; ?></h1>
    </div>
    <p class="lead"><?php echo $this->infoText; ?></p>

    <form method="post" action="/submit">

        <select class="form-control" name="role">
            <option>student</option>
            <option>ucitel</option>
        </select>

        <div class="checkbox">
            <label> <input type="checkbox" name="candidates" value="1">Candidate1
            </label>
        </div>
        <div class="checkbox">
            <label> <input type="checkbox" name="candidates" value="2">Candidate2
            </label>
        </div>
        <div class="checkbox">
            <label> <input type="checkbox" name="candidates" value="3">Candidate3
            </label>
        </div>

        <input type="submit" name="submit" value="Submit" class="btn btn-primary">
    </form>

</div>

