<?php echo $this->mainNavbar; ?>

<!-- BEGIN page container -->
<div class="container container-page">
    <div class="page-header">
        <h1><?php echo $this->translate('form_title'); ?></h1>
    </div>
    <p class="lead"><?php echo $this->translate('form_info_text'); ?></p>

    <form method="post" action="/confirm">

        <?php foreach ($this->candidates as $candidate) { ?>
        <div class="checkbox">
            <label> <input type="checkbox" name="candidates[]" value="<?php echo $candidate->getId(); ?>">
            <?php printf("%s %s", $candidate->getFirstName(), $candidate->getLastName()); ?>
            </label>
        </div>
        <?php } ?>

        <br>
        <input type="hidden" name="role" value="<?php echo $this->role; ?>">
        <input type="submit" name="submit" value="<?php echo $this->translate('form_button_submit'); ?>"
            class="btn btn-primary">
    </form>
</div>
<!-- END page container -->

