<?php echo $this->mainNavbar; ?>


<!-- Begin page content -->
<div class="container container-page">
    <div class="page-header">
        <h1><?php echo $this->translate('role_title'); ?></h1>
    </div>
    <p class="lead"><?php printf($this->translate('role_info_text'), $this->electoralName); ?></p>

    <form method="post" action="<?php echo $this->url('role'); ?>">

        <div class="radio">
            <label> <input type="radio" name="role" id="optionsRadios1" value="student">
                <?php echo $this->translate('role_student'); ?>
            </label>
        </div>
        <div class="radio">
            <label> <input type="radio" name="role" id="optionsRadios2" value="academic">
                <?php echo $this->translate('role_academic'); ?>
            </label>
        </div>

        <br>
        <div>
            <input type="submit" name="submit" value="<?php echo $this->translate('role_submit'); ?>"
                class="btn btn-primary">
        </div>
    </form>

</div>