<?php echo $this->mainNavbar; ?>


<!-- Begin page content -->
<div class="container container-page">
    <div class="page-header">
        <h1><?php echo $this->heading; ?></h1>
    </div>
    <p class="lead"><?php echo $this->infoText; ?></p>

    <form method="post" action="/submit">

        <select class="form-control" name="role">
            <option>student</option>
            <option>ucitel</option>
        </select> <br>
        <div>
            <input type="submit" name="submit" value="Submit" class="btn btn-primary">
        </div>
    </form>

</div>