<!DOCTYPE html>
<html lang="en">
<head>
<title><?php echo $this->translate('title_global'); ?></title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link href="<?php echo $this->basePath('css/bootstrap.min.css'); ?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath('css/custom.css'); ?>" media="screen" rel="stylesheet" type="text/css">

</head>

<body>   
<?php echo $this->content; ?>

<!-- 
<script src="https://code.jquery.com/jquery.js"></script>
-->
<script src="<?php echo $this->basePath('js/jquery-1.10.2.min.js'); ?>"></script>
<script src="<?php echo $this->basePath('js/bootstrap.min.js'); ?>"></script>
</body>
</html>